### ISSUE TITLE
Call to undefined function yaml_parse_file()

### ISSUE THREAD

**Issue by dashZdash** [JaxkDev/DiscordBot#19]
Fatal error: Uncaught Error: Call to undefined function yaml_parse_file() in C:\DIR2folder\BUILD.php:134
Stack trace:
#0 C:\DIR2folder\BUILD.php(28): generatePluginMetadataFromYml('C:\\Users\\night\\...')
#1 {main}
  thrown in C:\DIR2folder\BUILD.php on line 134

**Comment by JaxkDev** [comment]
Technically you can build without this but this is just straight out from dev tools.
Whatever PHP your using to run build.php it doesn’t have the yaml extension installed.
Either use prebuilt releases (https://github.com/JaxkDev/DiscordBot/releases) or install the extension, I won’t be helping further then that because you’d be running a unreleased version which can be unstable and potentially cause breakages in the future.
